root_desc: Open FAI de Ala Delta de Pedro Bernardo
description: Página del Open de Ala Delta de Pedro Bernardo (Ávila)
email: opendeltietar@googlegroups.com
server: true
auto: true
destination: _site/open
url: http://tercer.opendepb.com
#url: http://localhost:4000
exclude: bin, fs_templates, tmp
paginate: 4
